fix(logging): bump logback to get newer version than 1.7.x of slf4j (#394)
* fixes #388 by upgrading slf4j to 2.x
* spring boot tests were failing due to Spring 2.7.x requiring slf4j 1.7.x
* added spring.factories to prevent Spring from using its LoggingSystemLogback class causing a NoClassDefFoundError on class removed from slf4j 2.x
* add sample docker-compose.yaml to easily test standalone mode